TYPE=VIEW
query=select date_format(`cslmanager`.`workshop_attempt`.`debut`,\'%d %b %Y\') AS `Date`,time_format(`cslmanager`.`workshop_attempt`.`debut`,\'%H:%i\') AS `Debut`,`cslmanager`.`user`.`upn` AS `upn`,ifnull(`cslmanager`.`user`.`name`,substring_index(substring_index(`cslmanager`.`user`.`upn`,\'@\',1),\'.\',-(1))) AS `name`,ifnull(`cslmanager`.`user`.`first_name`,substring_index(substring_index(`cslmanager`.`user`.`upn`,\'@\',1),\'.\',1)) AS `FirstName`,`cslmanager`.`user`.`description` AS `Promo`,`cslmanager`.`workshop`.`label` AS `Workshop`,`cslmanager`.`workshop`.`full_label` AS `WorkshopFull`,`cslmanager`.`room`.`description` AS `Room`,time_format(timediff(`cslmanager`.`workshop_attempt`.`fin`,`cslmanager`.`workshop_attempt`.`debut`),\'%Hh, %im, %ss\') AS `Duration`,`cslmanager`.`scale`.`label` AS `Scale` from (`cslmanager`.`room` join (((`cslmanager`.`workshop_attempt` join `cslmanager`.`user` on((`cslmanager`.`workshop_attempt`.`id_user` = `cslmanager`.`user`.`id`))) join `cslmanager`.`workshop` on((`cslmanager`.`workshop`.`id` = `cslmanager`.`workshop_attempt`.`id_workshop`))) join `cslmanager`.`scale` on((`cslmanager`.`scale`.`scale_item_code` = `cslmanager`.`workshop_attempt`.`scale`)))) where ((`cslmanager`.`room`.`id` = `cslmanager`.`workshop`.`id_room`) and (`cslmanager`.`workshop_attempt`.`fin` is not null)) order by `cslmanager`.`workshop_attempt`.`debut`
md5=494211394c5d06e5d5e3e924f499a166
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-02-04 09:47:10
create-version=1
source=select date_format(`workshop_attempt`.`debut`,\'%d %b %Y\') AS `Date`,time_format(`workshop_attempt`.`debut`,\'%H:%i\') AS `Debut`,`user`.`upn` AS `upn`,ifnull(`user`.`name`,substring_index(substring_index(`user`.`upn`,\'@\',1),\'.\',-(1))) AS `name`,ifnull(`user`.`first_name`,substring_index(substring_index(`user`.`upn`,\'@\',1),\'.\',1)) AS `FirstName`,`user`.`description` AS `Promo`,`workshop`.`label` AS `Workshop`,`workshop`.`full_label` AS `WorkshopFull`,`room`.`description` AS `Room`,time_format(timediff(`workshop_attempt`.`fin`,`workshop_attempt`.`debut`),\'%Hh, %im, %ss\') AS `Duration`,`scale`.`label` AS `Scale` from (`room` join (((`workshop_attempt` join `user` on((`workshop_attempt`.`id_user` = `user`.`id`))) join `workshop` on((`workshop`.`id` = `workshop_attempt`.`id_workshop`))) join `scale` on((`scale`.`scale_item_code` = `workshop_attempt`.`scale`)))) where ((`room`.`id` = `workshop`.`id_room`) and (`workshop_attempt`.`fin` is not null)) order by `workshop_attempt`.`debut`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select date_format(`cslmanager`.`workshop_attempt`.`debut`,\'%d %b %Y\') AS `Date`,time_format(`cslmanager`.`workshop_attempt`.`debut`,\'%H:%i\') AS `Debut`,`cslmanager`.`user`.`upn` AS `upn`,ifnull(`cslmanager`.`user`.`name`,substring_index(substring_index(`cslmanager`.`user`.`upn`,\'@\',1),\'.\',-(1))) AS `name`,ifnull(`cslmanager`.`user`.`first_name`,substring_index(substring_index(`cslmanager`.`user`.`upn`,\'@\',1),\'.\',1)) AS `FirstName`,`cslmanager`.`user`.`description` AS `Promo`,`cslmanager`.`workshop`.`label` AS `Workshop`,`cslmanager`.`workshop`.`full_label` AS `WorkshopFull`,`cslmanager`.`room`.`description` AS `Room`,time_format(timediff(`cslmanager`.`workshop_attempt`.`fin`,`cslmanager`.`workshop_attempt`.`debut`),\'%Hh, %im, %ss\') AS `Duration`,`cslmanager`.`scale`.`label` AS `Scale` from (`cslmanager`.`room` join (((`cslmanager`.`workshop_attempt` join `cslmanager`.`user` on((`cslmanager`.`workshop_attempt`.`id_user` = `cslmanager`.`user`.`id`))) join `cslmanager`.`workshop` on((`cslmanager`.`workshop`.`id` = `cslmanager`.`workshop_attempt`.`id_workshop`))) join `cslmanager`.`scale` on((`cslmanager`.`scale`.`scale_item_code` = `cslmanager`.`workshop_attempt`.`scale`)))) where ((`cslmanager`.`room`.`id` = `cslmanager`.`workshop`.`id_room`) and (`cslmanager`.`workshop_attempt`.`fin` is not null)) order by `cslmanager`.`workshop_attempt`.`debut`
