TYPE=VIEW
query=select `cslmanager`.`scale`.`label` AS `scale`,`cslmanager`.`user`.`upn` AS `upn`,`cslmanager`.`workshop_attempt`.`debut` AS `start`,`cslmanager`.`workshop`.`full_label` AS `label`,`cslmanager`.`workshop_comment`.`content` AS `comment`,`cslmanager`.`workshop_attempt`.`id_user` AS `idUser`,`cslmanager`.`workshop`.`id` AS `idWorkshop`,`cslmanager`.`workshop_attempt`.`id` AS `idWorkshopAttempt`,`cslmanager`.`scale`.`id_scale_type` AS `scale_type` from ((((`cslmanager`.`workshop_attempt` left join `cslmanager`.`scale` on((`cslmanager`.`scale`.`scale_item_code` = `cslmanager`.`workshop_attempt`.`scale`))) left join `cslmanager`.`user` on((`cslmanager`.`user`.`id` = `cslmanager`.`workshop_attempt`.`id_user`))) left join `cslmanager`.`workshop` on((`cslmanager`.`workshop`.`id` = `cslmanager`.`workshop_attempt`.`id_workshop`))) left join `cslmanager`.`workshop_comment` on(((`cslmanager`.`workshop_comment`.`id_workshop` = `cslmanager`.`workshop`.`id`) and (`cslmanager`.`workshop_comment`.`id_user` = `cslmanager`.`user`.`id`)))) where ((`cslmanager`.`workshop_attempt`.`fin` is not null) and (`cslmanager`.`workshop`.`deleted` <> 1)) order by `cslmanager`.`scale`.`order_scale` desc,`cslmanager`.`workshop`.`id`
md5=bfbe0621e5cb241cf904d2f39aa8b990
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-02-04 09:47:10
create-version=1
source=select `scale`.`label` AS `scale`,`user`.`upn` AS `upn`,`workshop_attempt`.`debut` AS `start`,`workshop`.`full_label` AS `label`,`workshop_comment`.`content` AS `comment`,`workshop_attempt`.`id_user` AS `idUser`,`workshop`.`id` AS `idWorkshop`,`workshop_attempt`.`id` AS `idWorkshopAttempt`,`scale`.`id_scale_type` AS `scale_type` from ((((`workshop_attempt` left join `scale` on((`scale`.`scale_item_code` = `workshop_attempt`.`scale`))) left join `user` on((`user`.`id` = `workshop_attempt`.`id_user`))) left join `workshop` on((`workshop`.`id` = `workshop_attempt`.`id_workshop`))) left join `workshop_comment` on(((`workshop_comment`.`id_workshop` = `workshop`.`id`) and (`workshop_comment`.`id_user` = `user`.`id`)))) where ((`workshop_attempt`.`fin` is not null) and (`workshop`.`deleted` <> 1)) order by `scale`.`order_scale` desc,`workshop`.`id`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `cslmanager`.`scale`.`label` AS `scale`,`cslmanager`.`user`.`upn` AS `upn`,`cslmanager`.`workshop_attempt`.`debut` AS `start`,`cslmanager`.`workshop`.`full_label` AS `label`,`cslmanager`.`workshop_comment`.`content` AS `comment`,`cslmanager`.`workshop_attempt`.`id_user` AS `idUser`,`cslmanager`.`workshop`.`id` AS `idWorkshop`,`cslmanager`.`workshop_attempt`.`id` AS `idWorkshopAttempt`,`cslmanager`.`scale`.`id_scale_type` AS `scale_type` from ((((`cslmanager`.`workshop_attempt` left join `cslmanager`.`scale` on((`cslmanager`.`scale`.`scale_item_code` = `cslmanager`.`workshop_attempt`.`scale`))) left join `cslmanager`.`user` on((`cslmanager`.`user`.`id` = `cslmanager`.`workshop_attempt`.`id_user`))) left join `cslmanager`.`workshop` on((`cslmanager`.`workshop`.`id` = `cslmanager`.`workshop_attempt`.`id_workshop`))) left join `cslmanager`.`workshop_comment` on(((`cslmanager`.`workshop_comment`.`id_workshop` = `cslmanager`.`workshop`.`id`) and (`cslmanager`.`workshop_comment`.`id_user` = `cslmanager`.`user`.`id`)))) where ((`cslmanager`.`workshop_attempt`.`fin` is not null) and (`cslmanager`.`workshop`.`deleted` <> 1)) order by `cslmanager`.`scale`.`order_scale` desc,`cslmanager`.`workshop`.`id`
